name: build-and-test

on:
  push:
    branches:
      - modularization
      - main
  pull_request:
    branches:
      - modularization
      - main

jobs:
  build:
    name: Build Apps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11.0.10'
          distribution: 'adopt'
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Setup Services Key
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_KEYSTORE }}" > google-services.json.asc
          gpg -d --passphrase "${{ secrets.GOOGLE_SERVICES_PASSPHRASE }}" --batch google-services.json.asc > android/app/google-services.json
      - name: Install pub Depedencies
        run: flutter pub get
      - name: Testing in Core Depedencies
        run: |
          cd core
          flutter test
      - name: Testing in Search
        run: |
          cd search
          flutter test
      - name: Testing in Watchlist
        run: |
          cd watchlist
          flutter test